version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: php
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    depends_on:
      - postgres
    networks:
      - fuzzy-logic-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./.docker/local-dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/symfony
    depends_on:
      - php
    networks:
      - fuzzy-logic-network

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fuzzy_logic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./.docker/local-dev/postgres/data:/var/lib/postgresql/data
    networks:
      - fuzzy-logic-network

networks:
  fuzzy-logic-network:

